const test=require('node:test'),assert=require('node:assert/strict');
const {create,key,backupKey,recoveryKey}=require('../dist/note-storage.js');
const note=id=>({id,text:'Workshop note'});
function setup(raw){const data=new Map(raw===undefined?[]:[[key,raw]]);const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};const repo=create({storage:()=>storage,validate:n=>typeof n.id==='string'&&typeof n.text==='string'});return {data,storage,repo};}
test('one malformed item cannot discard valid notes and original is preserved before save',()=>{const raw=JSON.stringify([note('a'),null,note('b')]);const {repo,data}=setup(raw);const r=repo.load();assert.equal(r.damaged,true);assert.deepEqual(r.notes,[note('a'),note('b')]);repo.save([...r.notes,note('c')]);assert.equal(data.get(recoveryKey),raw);assert.equal(JSON.parse(data.get(key)).length,3);});
test('malformed JSON is recoverable and not overwritten without a backup',()=>{const {repo,data}=setup('{broken');assert.equal(repo.load().damaged,true);assert.equal(repo.recovery(),'{broken');repo.save([note('a')]);assert.equal(data.get(recoveryKey),'{broken');});
test('quota failure creating a backup leaves original untouched',()=>{const raw=JSON.stringify([note('a')]);const {repo,storage,data}=setup(raw);repo.load();storage.setItem=()=>{throw Error('quota');};assert.throws(()=>repo.save([note('a'),note('b')]));assert.equal(data.get(key),raw);});
test('failed primary write preserves the original and previous backup',()=>{const raw=JSON.stringify([note('a')]);const {repo,storage,data}=setup(raw);repo.load();storage.setItem=(k,v)=>{if(k===key)throw Error('quota');data.set(k,v);};assert.throws(()=>repo.save([note('a'),note('b')]));assert.equal(data.get(key),raw);assert.equal(data.get(backupKey),raw);});
test('a stale tab cannot overwrite a newer collection',()=>{const {repo,data}=setup('[]');repo.load();const newer=JSON.stringify([note('new')]);data.set(key,newer);assert.throws(()=>repo.save([note('old')]),/another tab/);assert.equal(data.get(key),newer);});
test('unavailable storage cannot masquerade as an empty saved collection',()=>{let blocked=true;const repo=create({storage:()=>{if(blocked)throw Error();return {getItem:()=>null,setItem:()=>assert.fail('must not write')};},validate:()=>true});assert.equal(repo.load().unavailable,true);blocked=false;assert.throws(()=>repo.save([]),/Reload/);});
test('duplicate IDs and excess notes are preserved in recovery rather than silently discarded',()=>{const raw=JSON.stringify([...Array.from({length:501},(_,i)=>note(String(i))),note('1')]);const {repo,data}=setup(raw);const r=repo.load();assert.equal(r.notes.length,500);assert.equal(r.damaged,true);repo.save(r.notes);assert.equal(data.get(recoveryKey),raw);});
test('an existing different recovery copy is never silently overwritten',()=>{const {repo,data}=setup('[null]');repo.load();data.set(recoveryKey,'earlier damaged collection');assert.throws(()=>repo.save([note('a')]),/earlier recovery/);assert.equal(data.get(key),'[null]');assert.equal(data.get(recoveryKey),'earlier damaged collection');});
test('successful saves retain one bounded previous-good backup',()=>{const {repo,data}=setup('[]');repo.load();repo.save([note('a')]);repo.save([note('a'),note('b')]);assert.equal(data.size,2);assert.deepEqual(JSON.parse(data.get(backupKey)),[note('a')]);});
